export const items = {
  services: [
    {
      id: 1,
      title: "Patches",
      slug: "patches",
      desc: "Our soft inks are completely unnoticeable to the touch, which means you wont feel any discomfort on the back of your neck while wearing your shirt. ",
      label: "24/7 Support",
      label1: "Fast Delivery",
      label2: "High Standards!",
      image: "/a1.webp",
    },
    {
      id: 2,
      title: "Embroidery",
      slug: "embroidery",
      desc: "Our soft inks are completely unnoticeable to the touch, which means you wont feel any discomfort on the back of your neck while wearing your shirt. ",
      label: "24/7 Support",
      label1: "Fast Delivery",
      label2: "High Standards",
      image: "/a2.webp",
    },
    {
      id: 3,
      title: "Sticker",
      slug: "sticker",
      desc: "Our soft inks are completely unnoticeable to the touch, which means you wont feel any discomfort on the back of your neck while wearing your shirt.",
      label: "24/7 Support",
      label1: " Fast Delivery",
      label2: "High Standards",
      image: "/sti.webp",
    },
    {
      id: 4,
      title: "Tote Bags",
      slug: "tote-bags",
      desc: "Our soft inks are completely unnoticeable to the touch, which means you wont feel any discomfort on the back of your neck while wearing your shirt. ",
      label: "24/7 Support",
      label1: "Fast Delivery",
      label2: "High Standards!",
      image: "/a4.webp",
    },
    {
      id: 5,
      title: "Aprons",
      slug: "aprons",
      desc: "Our soft inks are completely unnoticeable to the touch, which means you wont feel any discomfort on the back of your neck while wearing your shirt.",
      label: "24/7 Support",
      label1: "Fast Delivery",
      label2: "High Standards",
      image: "/a5.webp",
    },
    {
      id: 6,
      title: "Promotional Product",
      slug: "promotional-product",
      desc: "Our soft inks are completely unnoticeable to the touch, which means you wont feel any discomfort on the back of your neck while wearing your shirt.",
      label: "24/7 Support",
      label1: " Fast Delivery",
      label2: "High Standards",
      image: "/a6.webp",
    },
  ],
};

export const sser = [
  {
    id: 7001,
    title: "Standard",
    desc: "2-week delivery by January 15 - January 22",
    label: "All products available",
  },
  {
    id: 7002,
    title: "Rush",
    desc: "1-week delivery by January 4",
    label: "Most products available",
  },
  {
    id: 7003,
    title: "Lightning",
    desc: "2-day delivery by December 27",
    label: "Selected products available",
  },
];
